version: "3"

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:3.8-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - db
      - rabbitmq
      - celery-beat

  celery:
    build: .
    command: celery -A kuclass_project worker -l info
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - db

  celery-beat:
    build: .
    command: celery -A kuclass_project beat -l info
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - db

volumes:
  postgres_data:
