# Generated by Django 3.2.18 on 2023-07-14 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0002_alter_lesson_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100, unique=True, verbose_name='Uuid')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('date_of_day', models.DateField(verbose_name='Date')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('repeat', models.CharField(choices=[('one', 'One'), ('all_weeks', 'All_weeks'), ('several', 'Several')], max_length=9, verbose_name='Repeat')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_lesson', to='lessons.lesson', verbose_name='Lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
