# Generated by Django 3.2.18 on 2023-07-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('grade', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], max_length=8, verbose_name='Grade')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
